# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true

  clean:
    desc: Clean build directory
    silent: true
    dir: out
    cmds:
      - rm -rf *

  build:
    desc: Build ls
    cmds:
      - mkdir -p out
      - task: clean
      - go build -o out/ls .

  run:
    desc: Run ls
    cmds:
      - cmd: go run .
        ignore_error: true
